sudo: false
language: node_js
node_js:
  - '7.9'
before_script:
- npm install -g istanbul eslint-plugin-import eslint-config-airbnb-base eslint  codeclimate-test-reporter
after_script:
- npm run coverage
- CODECLIMATE_REPO_TOKEN=2a59315bdd9159d3cdec8afcf86a5ee6c33f2a34a6d61f7989ef9a3e272ed9f1 codeclimate-test-reporter < coverage/lcov.info